name: Build Android APK with Buildozer

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade buildozer cython==0.29.36
        sudo apt-get update
        sudo apt-get install -y git zip unzip libffi-dev libgmp-dev

    # --- THIS IS THE NEW, ROBUST LICENSE ACCEPTANCE STEP ---
    - name: Find and Accept Android SDK licenses
      run: |
        # First, find the sdkmanager path, wherever it may be
        SDKMANAGER_PATH=$(find $ANDROID_HOME -name "sdkmanager" | head -n 1)
        if [ -z "$SDKMANAGER_PATH" ]; then
          echo "Could not find sdkmanager"
          exit 1
        fi
        # Now, accept the licenses using the found path
        yes | $SDKMANAGER_PATH --licenses

    - name: Build with Buildozer
      run: |
        buildozer --version
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: translator-apk
        path: bin/*.apk
