name: Build Android APK with Buildozer

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade buildozer cython==0.29.36
        sudo apt-get update
        sudo apt-get install -y git zip unzip libffi-dev libgmp-dev

    # --- THIS IS THE NEW, DEFINITIVE FIX ---
    # We are now manually installing the required tools and accepting the licenses
    # BEFORE we run the main build. This prevents all previous errors.
    - name: Manually prepare Android SDK and accept licenses
      run: |
        # Find the sdkmanager path robustly
        SDKMANAGER_PATH=$(find $ANDROID_HOME -name "sdkmanager" | head -n 1)
        if [ -z "$SDKMANAGER_PATH" ]; then
          echo "Could not find sdkmanager"
          exit 1
        fi
        
        # Manually install the exact build-tools version and accept the license in one go
        yes | $SDKMANAGER_PATH "build-tools;36.0.0" "platforms;android-31"
        
        # As a final guarantee, run the license acceptance for all other licenses
        yes | $SDKMANAGER_PATH --licenses

    - name: Build with Buildozer
      run: |
        buildozer --version
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: translator-apk
        path: bin/*.apk
